spring:
  application:
    name: calendar-service


---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://${username}:${password}@localhost:9000

  data:
    redis:
      host: localhost
      port: 6379
      password: localRedis


websocket:
  url: http://localhost:8580

---

spring:

  config:
    activate:
      on-profile: live

    import: "aws-secretsmanager:/secret/calendar,optional:configserver:http://${secrets.username}:${secrets.password}@config-server:9000"




